openapi: 3.0.0
info:
  title: Task API
  version: 1.0.0
  description: API documentation for Task API

paths:
  /tasks:
    get:
      summary: Retrieve all tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '200':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        userId:
          type: integer
      required:
        - title
        - userId

    TaskInput:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        userId:
          type: integer
      required:
        - title
        - userId
