services:
  taskdb:
    image: mysql:latest
    container_name: taskdb
    environment:
      MYSQL_ROOT_PASSWORD: task
      MYSQL_DATABASE: taskdb
    ports:
      - "3306:3306"  # Map container port 3306 to host port 3306

  testdb:
    image: mysql:latest
    container_name: testdb
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: taskdb
    ports:
      - "3307:3306"  # Map container port 3306 to host port 3307 for testdb
  
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: /swagger/swagger.yaml

  api:
    build:
      context: .  # Assuming your Dockerfile is in the root directory
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    environment:
      - MYSQL_HOST=taskdb
    ports:
      - "3001:3001"  # Map container port 3000 to host port 3000
    depends_on:
      - taskdb