services:
  taskdb:
    image: mysql:latest
    container_name: taskdb
    environment:
      MYSQL_ROOT_PASSWORD: task
      MYSQL_DATABASE: taskdb
    ports:
      - "3306:3306"

  testdb:
    image: mysql:latest
    container_name: testdb
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: taskdb
    ports:
      - "3307:3306"
  
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: /swagger/swagger.yaml

  api:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    environment:
      - MYSQL_HOST=taskdb  # Points to the dokcer service taskdb
    ports:
      - "3001:3001"
    depends_on:
      - taskdb